### ISSUE TITLE
Update readme with scripts

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/OpenDSJ-2018#15]
Annie, great work getting the front end started! 

Other than npm install && npm run, are there any other scripts that need to be added to the Readme for new or other contributors to get the project running locally @lilannie ?

**Comment by lilannie** [comment]
No, there are no other commands you should have to run in order to load the app.
I can add more instructions for newcomers to be onboard, such as: install npm, install git, etc.

To load the app, right now, just run:
`npm run build:dev` in one terminal
and `npm run server:dev` in another terminal

Or you can run the yarn equivalents:
`yarn run build:dev`
`yarn run server:dev`
